name: taximate
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  google_maps_flutter: ^2.2.0
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.5.5
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
